//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Active_Diagrams.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("330")]
        public int ADTaskPaneWidth {
            get {
                return ((int)(this["ADTaskPaneWidth"]));
            }
            set {
                this["ADTaskPaneWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int ADTaskPaneHeight {
            get {
                return ((int)(this["ADTaskPaneHeight"]));
            }
            set {
                this["ADTaskPaneHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("130")]
        public int ADTaskPaneColumnPropertyWidth {
            get {
                return ((int)(this["ADTaskPaneColumnPropertyWidth"]));
            }
            set {
                this["ADTaskPaneColumnPropertyWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("msoCTPDockPositionFloating")]
        public global::Microsoft.Office.Core.MsoCTPDockPosition ADTaskPaneDockPosition {
            get {
                return ((global::Microsoft.Office.Core.MsoCTPDockPosition)(this["ADTaskPaneDockPosition"]));
            }
            set {
                this["ADTaskPaneDockPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ADTaskPaneVisible {
            get {
                return ((bool)(this["ADTaskPaneVisible"]));
            }
            set {
                this["ADTaskPaneVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FindCaseSensitive {
            get {
                return ((bool)(this["FindCaseSensitive"]));
            }
            set {
                this["FindCaseSensitive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FindExactMatch {
            get {
                return ((bool)(this["FindExactMatch"]));
            }
            set {
                this["FindExactMatch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FindRegEx {
            get {
                return ((bool)(this["FindRegEx"]));
            }
            set {
                this["FindRegEx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectDiagramActivePage {
            get {
                return ((int)(this["SelectDiagramActivePage"]));
            }
            set {
                this["SelectDiagramActivePage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127")]
        public int SearchResultDiagramNameWidth {
            get {
                return ((int)(this["SearchResultDiagramNameWidth"]));
            }
            set {
                this["SearchResultDiagramNameWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("130")]
        public int SearchResultDiagramTypeWidth {
            get {
                return ((int)(this["SearchResultDiagramTypeWidth"]));
            }
            set {
                this["SearchResultDiagramTypeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("118")]
        public int SearchResultDiagramAuthorWidth {
            get {
                return ((int)(this["SearchResultDiagramAuthorWidth"]));
            }
            set {
                this["SearchResultDiagramAuthorWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("110")]
        public int SearchResultDiagramStereotypeWidth {
            get {
                return ((int)(this["SearchResultDiagramStereotypeWidth"]));
            }
            set {
                this["SearchResultDiagramStereotypeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 19")]
        public global::System.Drawing.Point PreviewLocation {
            get {
                return ((global::System.Drawing.Point)(this["PreviewLocation"]));
            }
            set {
                this["PreviewLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("282, 253")]
        public global::System.Drawing.Size PreviewSize {
            get {
                return ((global::System.Drawing.Size)(this["PreviewSize"]));
            }
            set {
                this["PreviewSize"] = value;
            }
        }
    }
}
